In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
import numpy as np 
import time 
import sys

l = range(1000)
print(sys.getsizeof(5) * len(l))

array = np.arange(1000)
print(array.size*array.itemsize)


28000
4000


In [8]:
import numpy as np
a = np.array([5,6,9])
a[0]

5

In [10]:
a = np.array([[1,2,8],[3,4,9],[5,6,7]])
a.ndim

2

In [12]:
a.itemsize

4

In [16]:
a = np.array([[1,2,8],[3,4,9],[5,6,7]], dtype = np.float64)
a.dtype

dtype('float64')

In [19]:
a

array([[1., 2., 8.],
       [3., 4., 9.],
       [5., 6., 7.]])

In [23]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.linspace(1,5,2)

array([1., 5.])

In [27]:
np.linspace(1,5,10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
n = [1,2,3]
n[0:3]

[1, 2, 3]

In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [41]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [47]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [57]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [59]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [61]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [65]:
result = np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [69]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [77]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [83]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
a + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.savetxt("test.txt", a)

In [95]:
y = np.loadtxt("test.txt")

In [7]:
data = loadtxt('data_file_1.csv', skiprows=9)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
a = np.arange(12).reshape(3,4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [22]:
for x in np.nditer(a, order='C', flags=['external_loop']):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
